name: reward
description: "A new Flutter project"
publish_to: 'none'
version: 1.0.0+9

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  provider: ^6.1.1
  dio: ^5.4.0
  flutter_svg: ^2.0.10
  google_sign_in: ^6.1.6
  url_launcher: ^6.2.2
  shared_preferences: ^2.3.3
  webview_flutter: ^4.0.0
  universal_html: ^2.2.4
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  intl: any
  connectivity_plus: ^5.0.2
  crypto: ^3.0.3
  kakao_flutter_sdk_user: ^1.9.1
  naver_login_sdk: ^3.0.2
  
  # Modern UI Libraries
  animations: ^2.0.11
  flutter_animate: ^4.5.0
  glass_kit: ^3.0.0
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  smooth_page_indicator: ^1.2.0+3
  cached_network_image: ^3.4.1
  
  # Enhanced Material Design
  dynamic_color: ^1.7.0
  material_color_utilities: ^0.11.1
  
  # Responsive Design
  responsive_framework: ^1.5.1
  
  # Charts and Data Visualization
  fl_chart: ^0.69.0
  
  # Haptic Feedback
  haptic_feedback: ^0.5.1+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700
