name: Deploy Flutter Web to Vercel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5' # 원하는 Flutter 버전을 입력
        channel: stable

    - name: Install dependencies
      run: flutter pub get

    - name: Build web
      run: flutter build web --release   --dart-define=ENV=prod

    - name: Deploy to Vercel
      run: |
        mv build/web build/reward-app
        cd build/reward-app
        npx vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
